[package]
name = "massa-sc-runtime"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
lazy_static = "1"
serde = "1.0"
serde_json = "1.0"
wasmer = "2.2.1"
as-ffi-bindings = { "git" = "https://github.com/massalabs/as-ffi-bindings.git", branch = "fix_memory_errors" }
wasmer-compiler-singlepass = "2.2.1"
wasmer-engine-universal = "2.2.1"
wasmer-middlewares = "2.2.1"
cornetto = "0.1.0"
base64 = "0.13.0"
serial_test = "0.5.1"
loupe = "0.1.3"
